apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-dependency
  namespace: kube-system
spec:
  project: default
  source:
    path: kube-system-dependency
    repoURL: https://github.com/keiSunagawa/lean-argo-cd
    targetRevision: 0.1.0
