apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-dependency
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-system-dependency
    repoURL: https://github.com/keiSunagawa/lean-argo-cd
    targetRevision: 0.1.0
